package com.nse.algotrading.model;

import java.time.LocalDateTime;

/**
 * Trading signal generated by a strategy.
 */
public class Signal {
    public enum Action { BUY, SELL, HOLD, EXIT_LONG, EXIT_SHORT }

    private Action action;
    private String symbol;
    private double price;
    private double stopLoss;
    private double target;
    private int suggestedQuantity;
    private String strategyName;
    private String reason;
    private LocalDateTime generatedAt;
    private double confidence;        // 0.0 to 1.0

    public Signal(Action action, String symbol, double price, String strategyName) {
        this.action = action;
        this.symbol = symbol;
        this.price = price;
        this.strategyName = strategyName;
        this.generatedAt = LocalDateTime.now();
        this.confidence = 1.0;
    }

    public boolean isBullish() {
        return action == Action.BUY;
    }

    public boolean isBearish() {
        return action == Action.SELL;
    }

    public boolean isExit() {
        return action == Action.EXIT_LONG || action == Action.EXIT_SHORT;
    }

    public double getRiskRewardRatio() {
        if (stopLoss <= 0 || target <= 0) return 0;
        double risk   = Math.abs(price - stopLoss);
        double reward = Math.abs(target - price);
        return risk == 0 ? 0 : reward / risk;
    }

    // Getters and Setters
    public Action getAction() { return action; }
    public void setAction(Action action) { this.action = action; }

    public String getSymbol() { return symbol; }
    public void setSymbol(String symbol) { this.symbol = symbol; }

    public double getPrice() { return price; }
    public void setPrice(double price) { this.price = price; }

    public double getStopLoss() { return stopLoss; }
    public void setStopLoss(double stopLoss) { this.stopLoss = stopLoss; }

    public double getTarget() { return target; }
    public void setTarget(double target) { this.target = target; }

    public int getSuggestedQuantity() { return suggestedQuantity; }
    public void setSuggestedQuantity(int suggestedQuantity) {
        this.suggestedQuantity = suggestedQuantity;
    }

    public String getStrategyName() { return strategyName; }
    public void setStrategyName(String strategyName) { this.strategyName = strategyName; }

    public String getReason() { return reason; }
    public void setReason(String reason) { this.reason = reason; }

    public LocalDateTime getGeneratedAt() { return generatedAt; }
    public void setGeneratedAt(LocalDateTime generatedAt) { this.generatedAt = generatedAt; }

    public double getConfidence() { return confidence; }
    public void setConfidence(double confidence) { this.confidence = confidence; }

    @Override
    public String toString() {
        return String.format("Signal[%s] %s @ %.2f SL=%.2f TGT=%.2f strategy=%s",
                action, symbol, price, stopLoss, target, strategyName);
    }
}
